### ISSUE TITLE
Deconvolution edge artefacts in z direction

### ISSUE THREAD

**Issue by davidcorcoran545** [warwickcamdu/PetaKit5DfromSLD#10]
We get edge artefacts in the deconvolution in the z-direction when there is signal in towards the edges of the stack. This is using the "simplified" version of deconvolution. I don't think there is any padding turned on by default, so we may have to manually pad. Should test different methods: zeros, minimum, mirror etc.

**Comment by scott-vision** [comment]
Hi David,

Thanks for bringing this up! We do indeed have the option to set padding to mitigate the edge artifacts in the z-direction. We can configure the padding type through the z_edge_padding parameter with options like 'none', 'zero', 'mirror', 'gaussian', or 'fixed'. By default, it's set to 'gaussian', but you can modify it as needed.

Additionally, there’s an adjustable z_padding parameter (default set to 20) to define the padding size. For Gaussian padding, we’ve preset parameters with a mean of 102.27 and a standard deviation of 3.17. For fixed padding, the value is set to 100.

Feel free to test these and let us know if they improve the results in your deconvolution!

Best,
Scott
